version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zoo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:root@db:5432/zoo
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
